### ISSUE TITLE
overwrite mode is broken

### ISSUE THREAD

**Issue by vjjjv** [caio-ribeiro-pereira/gzipme#5]
unlinkSync gets called too early, before the stream has finished

**Comment by vjjjv** [comment]
Are you going to update this to npm as well? I think there gzipme is 4 months old version.

**Comment by caio-ribeiro-pereira** [comment]
Hi @vjjjv for while, I'm not planning to maintain by myself this project, because I've been working in my own startup, but I can update the project, if you or anybody send me pull requests.
